name: Auto Assign Reviewers
on:
  pull_request:
    types:
      - opened

jobs:
  auto_assign_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Request changes
        uses: peter-evans/request-changes@v1
        with:
          reviewers: 'AndreyZlobin, AndyZlobin' # Замените на список логинов ревьюеров
          changes-requested-label: 'Changes Requested'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
