name: Auto Assign Reviewers
on:
  pull_request:
    types:
      - opened

jobs:
  auto_assign_reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Request changes
        uses: .github/actions/request-changes
        with:
          reviewers: 'AndreyZlobin, AndyZlobin' # Замените на список логинов ревьюеров
          changes-requested-label: 'Changes Requested'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
